#!/bin/bash

calculate_percentage()
{
 local PARAMETER_INTEGER_VALUE="$1"
 local PARAMETER_INTEGER_100PERCENTAGE="$2"

 local LOCAL_INTEGER_HUNDREDPERCENTAGE

 if [ $PARAMETER_INTEGER_VALUE -le 0 ]
 then
  echo "0.00"
  return
 fi

 if [ $PARAMETER_INTEGER_100PERCENTAGE -le 0 ]
 then
  echo "0.00"
  return
 fi

 LOCAL_INTEGER_HUNDREDPERCENTAGE="$(( PARAMETER_INTEGER_VALUE * 10000 / $PARAMETER_INTEGER_100PERCENTAGE ))"

 if [ $LOCAL_INTEGER_HUNDREDPERCENTAGE -eq 0 ]
 then
  echo "0.00"
  return
 fi

 LOCAL_INTEGER_HUNDREDPERCENTAGE=$(printf "%03d" $LOCAL_INTEGER_HUNDREDPERCENTAGE)

 echo "${LOCAL_INTEGER_HUNDREDPERCENTAGE:0:-2}.${LOCAL_INTEGER_HUNDREDPERCENTAGE: -2}"
}
