#!/bin/bash

convert_byte_megabyte()
{
 local PARAMETER_INTEGER_BYTE="$1"

 local LOCAL_INTEGER_HUNDREDMEGABYTE

 LOCAL_INTEGER_HUNDREDMEGABYTE="$(( PARAMETER_INTEGER_BYTE * 100 / 1048576 ))"
 LOCAL_INTEGER_HUNDREDMEGABYTE="$(printf '%03d' $LOCAL_INTEGER_HUNDREDMEGABYTE)"

 echo "${LOCAL_INTEGER_HUNDREDMEGABYTE:0:-2}.${LOCAL_INTEGER_HUNDREDMEGABYTE: -2}"
}

convert_kilobyte_megabyte()
{
 local PARAMETER_INTEGER_KILOBYTE="$1"

 local LOCAL_INTEGER_HUNDREDMEGABYTE

 LOCAL_INTEGER_HUNDREDMEGABYTE="$(( PARAMETER_INTEGER_KILOBYTE * 100 / 1024 ))"
 LOCAL_INTEGER_HUNDREDMEGABYTE="$(printf '%03d' $LOCAL_INTEGER_HUNDREDMEGABYTE)"

 echo "${LOCAL_INTEGER_HUNDREDMEGABYTE:0:-2}.${LOCAL_INTEGER_HUNDREDMEGABYTE: -2}"
}

convert_filewithheader_namevalue()
{
 local PARAMETER_FILE_SOURCE="$1"
 local -n PARAMETER_STRING_FIRSTLINE="$2"
 local -n PARAMETER_ARRAY_RESULT="$3"

 local LOCAL_INTEGER_FILELINE
 local LOCAL_STRING_SOURCE
 local LOCAL_LINESTRING_SOURCE
 local LOCAL_STRING_NAME
 local LOCAL_STRING_VALUE

 PARAMETER_ARRAY_RESULT=()
 LOCAL_INTEGER_FILELINE="1"

 LOCAL_STRING_SOURCE=$(<"$PARAMETER_FILE_SOURCE")

 IFS=$'\n'
 for LOCAL_LINESTRING_SOURCE in $LOCAL_STRING_SOURCE
 do
  if [ "$LOCAL_INTEGER_FILELINE" = "1" ]
  then
   PARAMETER_STRING_FIRSTLINE="$LOCAL_LINESTRING_SOURCE"
   LOCAL_INTEGER_FILELINE=2
   continue
  fi

  if [ "$LOCAL_INTEGER_FILELINE" = "2" ]
  then
   LOCAL_INTEGER_FILELINE=3
   continue
  fi

  LOCAL_STRING_NAME="${LOCAL_LINESTRING_SOURCE%% *}"
  LOCAL_STRING_VARIABLE="${LOCAL_LINESTRING_SOURCE##* }"

  PARAMETER_ARRAY_RESULT["$LOCAL_STRING_NAME"]="$LOCAL_STRING_VARIABLE"
 done
}

convert_filewithkb_namevalue()
{
 local PARAMETER_FILE_SOURCE="$1"
 local PARAMETER_INTEGER_LINES="$2"
 local -n PARAMETER_ARRAY_RESULT="$3"

 local LOCAL_INTEGER_LINE
 local LOCAL_LINESTRING_SOURCE
 local LOCAL_STRING_NAME
 local LOCAL_STRING_VALUE

 PARAMETER_ARRAY_RESULT=()
 LOCAL_INTEGER_LINE=0

 while read LOCAL_LINESTRING_SOURCE
 do
  LOCAL_STRING_NAME="${LOCAL_LINESTRING_SOURCE%%:*}"
  LOCAL_STRING_VARIABLE="${LOCAL_LINESTRING_SOURCE#*:}"
  LOCAL_STRING_VARIABLE="${LOCAL_STRING_VARIABLE:0:-3}"

  PARAMETER_ARRAY_RESULT["$LOCAL_STRING_NAME"]="$LOCAL_STRING_VARIABLE"

  (( LOCAL_INTEGER_LINE++ ))

  if [ "$LOCAL_INTEGER_LINE" -ge "$PARAMETER_INTEGER_LINES" ]
  then
   break
  fi
 done < "$PARAMETER_FILE_SOURCE"
}
