#!/bin/bash

print_percentagebar20()
{
 local PARAMETER_INTEGER_1PERCENTAGE20="$1"
 local PARAMETER_STRING_VALUE1="$2"
 local PARAMETER_STRING_VALUE2="$3"

 local LOCAL_INTEGER_INDEX
 local LOCAL_INTEGER_2PERCENTAGE20

 if [ $PARAMETER_INTEGER_1PERCENTAGE20 -gt 20 ]
 then
  return
 fi

 echo -n "$PARAMETER_STRING_VALUE1 "

 for(( LOCAL_INTEGER_INDEX=0; LOCAL_INTEGER_INDEX<PARAMETER_INTEGER_1PERCENTAGE20; LOCAL_INTEGER_INDEX++ ))
 do
  echo -en "\u2588"
 done

 LOCAL_INTEGER_2PERCENTAGE20=$(( 20 - $PARAMETER_INTEGER_1PERCENTAGE20 ))

 for(( LOCAL_INTEGER_INDEX=0; LOCAL_INTEGER_INDEX<LOCAL_INTEGER_2PERCENTAGE20; LOCAL_INTEGER_INDEX++ ))
 do
  echo -en "\u2592"
 done

 echo " $PARAMETER_STRING_VALUE2"
}

print_4percentagebarmaximum20()
{
 local PARAMETER_INTEGER_1PERCENTAGE20="$1"
 local PARAMETER_INTEGER_2PERCENTAGE20="$2"
 local PARAMETER_INTEGER_3PERCENTAGE20="$3"
 local PARAMETER_INTEGER_4PERCENTAGE20="$4"
 local PARAMETER_STRING_VALUE12="$5"
 local PARAMETER_STRING_VALUE34="$6"

 local LOCAL_INTEGER_123PERCENTAGE20
 local LOCAL_INTEGER_INDEX

 LOCAL_INTEGER_PERCENTAGE20=$(( $PARAMETER_INTEGER_1PERCENTAGE20 + $PARAMETER_INTEGER_2PERCENTAGE20 + $PARAMETER_INTEGER_3PERCENTAGE20 + $PARAMETER_INTEGER_4PERCENTAGE20 ))

 if [ $LOCAL_INTEGER_PERCENTAGE20 -gt 20 ]
 then
  return
 fi

 echo -n "$PARAMETER_STRING_VALUE12 "

 for(( LOCAL_INTEGER_INDEX=0; LOCAL_INTEGER_INDEX<PARAMETER_INTEGER_1PERCENTAGE20; LOCAL_INTEGER_INDEX++ ))
 do
  echo -en "\u2588"
 done

 for(( LOCAL_INTEGER_INDEX=0; LOCAL_INTEGER_INDEX<PARAMETER_INTEGER_2PERCENTAGE20; LOCAL_INTEGER_INDEX++ ))
 do
  echo -en "\u2593"
 done

 for(( LOCAL_INTEGER_INDEX=0; LOCAL_INTEGER_INDEX<PARAMETER_INTEGER_3PERCENTAGE20; LOCAL_INTEGER_INDEX++ ))
 do
  echo -en "\u2592"
 done

 for(( LOCAL_INTEGER_INDEX=0; LOCAL_INTEGER_INDEX<PARAMETER_INTEGER_4PERCENTAGE20; LOCAL_INTEGER_INDEX++ ))
 do
  echo -en "\u2591"
 done

 echo " $PARAMETER_STRING_VALUE34"
}

print_zpool_status()
{
 /sbin/zpool status
}

print_zpool_verbosediostat()
{
 /sbin/zpool iostat -v
}

print_system_memory()
{
 echo "System Memory:"
 /usr/bin/head -n 6 /proc/meminfo
}

print_arcsize_total()
{
 local -n PARAMETER_ARRAY_ARCSTATS="$1"

 echo -e "
Arc Size - Total:
 \u2022 Current Size (size):
      ${PARAMETER_ARRAY_ARCSTATS[size]} ($(convert_byte_megabyte ${PARAMETER_ARRAY_ARCSTATS[size]}) MB)
 \u2022 Target Size (c):
      ${PARAMETER_ARRAY_ARCSTATS[c]} ($(convert_byte_megabyte ${PARAMETER_ARRAY_ARCSTATS[c]}) MB)
 \u2022 Minimum Size (c_min):
      ${PARAMETER_ARRAY_ARCSTATS[c_min]} ($(convert_byte_megabyte ${PARAMETER_ARRAY_ARCSTATS[c_min]}) MB)
 \u2022 Maximum Size (c_max):
      ${PARAMETER_ARRAY_ARCSTATS[c_max]} ($(convert_byte_megabyte ${PARAMETER_ARRAY_ARCSTATS[c_max]}) MB)"
}

print_arcsize_breakdown()
{
 local -n PARAMETER_ARRAY_ARCSTATS="$1"

 local LOCAL_INTEGER_MFU

 LOCAL_INTEGER_MFU=$(( ${PARAMETER_ARRAY_ARCSTATS[c]} - ${PARAMETER_ARRAY_ARCSTATS[p]} ))

 echo -e "
ARC Size - Breakdown:
 \u2022 Most Recently Used Cache Size (p):
      ${PARAMETER_ARRAY_ARCSTATS[p]} ($(convert_byte_megabyte ${PARAMETER_ARRAY_ARCSTATS[p]}) MB - $(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[p]} ${PARAMETER_ARRAY_ARCSTATS[c]})%)
 \u2022 Most Frequently Used Cache Size (c-p):
      $LOCAL_INTEGER_MFU ($(convert_byte_megabyte $LOCAL_INTEGER_MFU) MB - $(calculate_percentage $LOCAL_INTEGER_MFU ${PARAMETER_ARRAY_ARCSTATS[c]})%)"
}

print_arcefficiency_total()
{
 local -n PARAMETER_ARRAY_ARCSTATS="$1"
 local -n PARAMETER_ARRAY_ARCSTATSLOG="$2"

 local LOCAL_INTEGER_TOTAL
 local LOCAL_INTEGER_TOTALLOG
 local LOCAL_INTEGER_TOTALDELTA
 local LOCAL_INTEGER_HITSPERCENTAGE
 local LOCAL_INTEGER_HITSDELTA
 local LOCAL_INTEGER_HITSDELTAPERCENTAGE
 local LOCAL_INTEGER_MISSESPERCENTAGE
 local LOCAL_INTEGER_MISSESDELTA
 local LOCAL_INTEGER_MISSESDELTAPERCENTAGE
 local LOCAL_INTEGER_REALHITS
 local LOCAL_INTEGER_REALHITSLOG
 local LOCAL_INTEGER_REALHITSDELTA

 LOCAL_INTEGER_TOTAL=$(( ${PARAMETER_ARRAY_ARCSTATS[hits]} + ${PARAMETER_ARRAY_ARCSTATS[misses]} ))
 LOCAL_INTEGER_TOTALLOG=$(( ${PARAMETER_ARRAY_ARCSTATSLOG[hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[misses]} ))
 LOCAL_INTEGER_TOTALDELTA=$(( $LOCAL_INTEGER_TOTAL - $LOCAL_INTEGER_TOTALLOG))

 LOCAL_INTEGER_HITSPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[hits]} $LOCAL_INTEGER_TOTAL)
 LOCAL_INTEGER_HITSDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[hits]} ))
 LOCAL_INTEGER_HITSDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_HITSDELTA $LOCAL_INTEGER_TOTALDELTA)

 LOCAL_INTEGER_MISSESPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[misses]} $LOCAL_INTEGER_TOTAL)
 LOCAL_INTEGER_MISSESDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[misses]} ))
 LOCAL_INTEGER_MISSESDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_MISSESDELTA $LOCAL_INTEGER_TOTALDELTA)

 LOCAL_INTEGER_REALHITS=$(( ${PARAMETER_ARRAY_ARCSTATS[mru_hits]} + ${PARAMETER_ARRAY_ARCSTATS[mfu_hits]} ))
 LOCAL_INTEGER_REALHITSLOG=$(( ${PARAMETER_ARRAY_ARCSTATSLOG[mru_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[mfu_hits]} ))
 LOCAL_INTEGER_REALHITSDELTA=$(( $LOCAL_INTEGER_REALHITS - $LOCAL_INTEGER_REALHITSLOG))

 echo -e "
ARC Efficiency - Total:
 \u2022 Cache Access Total:
      $LOCAL_INTEGER_TOTAL \u279f $LOCAL_INTEGER_TOTALLOG - \u0394$LOCAL_INTEGER_TOTALDELTA
 \u2022 Cache Hits (hits):
      ${PARAMETER_ARRAY_ARCSTATS[hits]} ($LOCAL_INTEGER_HITSPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[hits]} - \u0394$LOCAL_INTEGER_HITSDELTA (\u0394$LOCAL_INTEGER_HITSDELTAPERCENTAGE%)
 \u2022 Cache Misses (misses):
      ${PARAMETER_ARRAY_ARCSTATS[misses]} ($LOCAL_INTEGER_MISSESPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[misses]} - \u0394$LOCAL_INTEGER_MISSESDELTA (\u0394$LOCAL_INTEGER_MISSESDELTAPERCENTAGE%)
 \u2022 Real Cache Hits (mru_hits + mfu_hits):
      $LOCAL_INTEGER_REALHITS ($(calculate_percentage $LOCAL_INTEGER_REALHITS $LOCAL_INTEGER_TOTAL)%) \u279f $LOCAL_INTEGER_REALHITSLOG - \u0394$LOCAL_INTEGER_REALHITSDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_REALHITSDELTA $LOCAL_INTEGER_TOTALDELTA)%)"

 if ! ( [ "$LOCAL_INTEGER_HITSPERCENTAGE" = "0.00" ] && [ "$LOCAL_INTEGER_MISSESPERCENTAGE" = "0.00" ] )
 then
  echo "
   $(print_percentagebar20 $(( ${LOCAL_INTEGER_HITSPERCENTAGE:0:-3} / 5 )) "Hits ($LOCAL_INTEGER_HITSPERCENTAGE%)" "Misses ($LOCAL_INTEGER_MISSESPERCENTAGE%)")"
 fi
}

print_arcefficiency_breakdown()
{
 local -n PARAMETER_ARRAY_ARCSTATS="$1"
 local -n PARAMETER_ARRAY_ARCSTATSLOG="$2"

 local LOCAL_INTEGER_DEMANDDATATOTAL
 local LOCAL_INTEGER_DEMANDDATATOTALLOG
 local LOCAL_INTEGER_DEMANDDATATOTALDELTA
 local LOCAL_INTEGER_DEMANDDATAHITSPERCENTAGE
 local LOCAL_INTEGER_DEMANDDATAHITSDELTA
 local LOCAL_INTEGER_DEMANDDATAHITSDELTAPERCENTAGE
 local LOCAL_INTEGER_DEMANDDATAMISSESPERCENTAGE
 local LOCAL_INTEGER_DEMANDDATAMISSESDELTA
 local LOCAL_INTEGER_DEMANDDATAMISSESDELTAPERCENTAGE
 local LOCAL_INTEGER_DEMANDMETADATATOTAL
 local LOCAL_INTEGER_DEMANDMETADATATOTALLOG
 local LOCAL_INTEGER_DEMANDMETADATATOTALDELTA
 local LOCAL_INTEGER_DEMANDMETADATAHITSPERCENTAGE
 local LOCAL_INTEGER_DEMANDMETADATAHITSDELTA
 local LOCAL_INTEGER_DEMANDMETADATAHITSDELTAPERCENTAGE
 local LOCAL_INTEGER_DEMANDMETADATAMISSESPERCENTAGE
 local LOCAL_INTEGER_DEMANDMETADATAMISSESDELTA
 local LOCAL_INTEGER_DEMANDMETADATAMISSESDELTAPERCENTAGE
 local LOCAL_INTEGER_PREFETCHDATATOTAL
 local LOCAL_INTEGER_PREFETCHDATATOTALLOG
 local LOCAL_INTEGER_PREFETCHDATATOTALDELTA
 local LOCAL_INTEGER_PREFETCHDATAHITSPERCENTAGE
 local LOCAL_INTEGER_PREFETCHDATAHITSDELTA
 local LOCAL_INTEGER_PREFETCHDATAHITSDELTAPERCENTAGE
 local LOCAL_INTEGER_PREFETCHDATAMISSESPERCENTAGE
 local LOCAL_INTEGER_PREFETCHDATAMISSESDELTA
 local LOCAL_INTEGER_PREFETCHDATAMISSESDELTAPERCENTAGE
 local LOCAL_INTEGER_PREFETCHMETADATATOTAL
 local LOCAL_INTEGER_PREFETCHMETADATATOTALLOG
 local LOCAL_INTEGER_PREFETCHMETADATATOTALDELTA
 local LOCAL_INTEGER_PREFETCHMETADATAHITSPERCENTAGE
 local LOCAL_INTEGER_PREFETCHMETADATAHITSDELTA
 local LOCAL_INTEGER_PREFETCHMETADATAHITSDELTAPERCENTAGE
 local LOCAL_INTEGER_PREFETCHMETADATAMISSESPERCENTAGE
 local LOCAL_INTEGER_PREFETCHMETADATAMISSESDELTA
 local LOCAL_INTEGER_PREFETCHMETADATAMISSESDELTAPERCENTAGE

 LOCAL_INTEGER_DEMANDDATATOTAL=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_data_hits]} + ${PARAMETER_ARRAY_ARCSTATS[demand_data_misses]} ))
 LOCAL_INTEGER_DEMANDDATATOTALLOG=$(( ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_misses]} ))
 LOCAL_INTEGER_DEMANDDATATOTALDELTA=$(( $LOCAL_INTEGER_DEMANDDATATOTAL - $LOCAL_INTEGER_DEMANDDATATOTALLOG ))

 LOCAL_INTEGER_DEMANDDATAHITSPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[demand_data_hits]} $LOCAL_INTEGER_DEMANDDATATOTAL)
 LOCAL_INTEGER_DEMANDDATAHITSDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_data_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_hits]} ))
 LOCAL_INTEGER_DEMANDDATAHITSDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_DEMANDDATAHITSDELTA $LOCAL_INTEGER_DEMANDDATATOTALDELTA)

 LOCAL_INTEGER_DEMANDDATAMISSESPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[demand_data_misses]} $LOCAL_INTEGER_DEMANDDATATOTAL)
 LOCAL_INTEGER_DEMANDDATAMISSESDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_data_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_misses]} ))
 LOCAL_INTEGER_DEMANDDATAMISSESDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_DEMANDDATAMISSESDELTA $LOCAL_INTEGER_DEMANDDATATOTALDELTA)

 LOCAL_INTEGER_DEMANDMETADATATOTAL=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_hits]} + ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_misses]} ))
 LOCAL_INTEGER_DEMANDMETADATATOTALLOG=$(( ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_misses]} ))
 LOCAL_INTEGER_DEMANDMETADATATOTALDELTA=$(( $LOCAL_INTEGER_DEMANDMETADATATOTAL - $LOCAL_INTEGER_DEMANDMETADATATOTALLOG ))

 LOCAL_INTEGER_DEMANDMETADATAHITSPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_hits]} $LOCAL_INTEGER_DEMANDMETADATATOTAL)
 LOCAL_INTEGER_DEMANDMETADATAHITSDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_hits]} ))
 LOCAL_INTEGER_DEMANDMETADATAHITSDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_DEMANDMETADATAHITSDELTA $LOCAL_INTEGER_DEMANDMETADATATOTALDELTA)

 LOCAL_INTEGER_DEMANDMETADATAMISSESPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_misses]} $LOCAL_INTEGER_DEMANDMETADATATOTAL)
 LOCAL_INTEGER_DEMANDMETADATAMISSESDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_misses]} ))
 LOCAL_INTEGER_DEMANDMETADATAMISSESDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_DEMANDMETADATAMISSESDELTA $LOCAL_INTEGER_DEMANDMETADATATOTALDELTA)

 LOCAL_INTEGER_PREFETCHDATATOTAL=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_hits]} + ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_misses]} ))
 LOCAL_INTEGER_PREFETCHDATATOTALLOG=$(( ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_misses]} ))
 LOCAL_INTEGER_PREFETCHDATATOTALDELTA=$(( $LOCAL_INTEGER_PREFETCHDATATOTAL - $LOCAL_INTEGER_PREFETCHDATATOTALLOG ))

 LOCAL_INTEGER_PREFETCHDATAHITSPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_hits]} $LOCAL_INTEGER_PREFETCHDATATOTAL)
 LOCAL_INTEGER_PREFETCHDATAHITSDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_hits]} ))
 LOCAL_INTEGER_PREFETCHDATAHITSDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_PREFETCHDATAHITSDELTA $LOCAL_INTEGER_PREFETCHDATATOTALDELTA)

 LOCAL_INTEGER_PREFETCHDATAMISSESPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_misses]} $LOCAL_INTEGER_PREFETCHDATATOTAL)
 LOCAL_INTEGER_PREFETCHDATAMISSESDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_misses]} ))
 LOCAL_INTEGER_PREFETCHDATAMISSESDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_PREFETCHDATAMISSESDELTA $LOCAL_INTEGER_PREFETCHDATATOTALDELTA)

 LOCAL_INTEGER_PREFETCHMETADATATOTAL=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_hits]} + ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_misses]} ))
 LOCAL_INTEGER_PREFETCHMETADATATOTALLOG=$(( ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_misses]} ))
 LOCAL_INTEGER_PREFETCHMETADATATOTALDELTA=$(( $LOCAL_INTEGER_PREFETCHMETADATATOTAL - $LOCAL_INTEGER_PREFETCHMETADATATOTALLOG ))

 LOCAL_INTEGER_PREFETCHMETADATAHITSPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_hits]} $LOCAL_INTEGER_PREFETCHMETADATATOTAL)
 LOCAL_INTEGER_PREFETCHMETADATAHITSDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_hits]} ))
 LOCAL_INTEGER_PREFETCHMETADATAHITSDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_PREFETCHMETADATAHITSDELTA $LOCAL_INTEGER_PREFETCHMETADATATOTALDELTA)

 LOCAL_INTEGER_PREFETCHMETADATAMISSESPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_misses]} $LOCAL_INTEGER_PREFETCHMETADATATOTAL)
 LOCAL_INTEGER_PREFETCHMETADATAMISSESDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_misses]} ))
 LOCAL_INTEGER_PREFETCHMETADATAMISSESDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_PREFETCHMETADATAMISSESDELTA $LOCAL_INTEGER_PREFETCHMETADATATOTALDELTA)

 echo -e "
ARC Efficiency - Breakdown:
 \u2022 Demand Data Hits (demand_data_hits):
      ${PARAMETER_ARRAY_ARCSTATS[demand_data_hits]} ($LOCAL_INTEGER_DEMANDDATAHITSPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_hits]} - \u0394$LOCAL_INTEGER_DEMANDDATAHITSDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_DEMANDDATAHITSDELTA $LOCAL_INTEGER_DEMANDDATATOTALDELTA)%)
 \u2022 Demand Data Misses (demand_data_misses):
      ${PARAMETER_ARRAY_ARCSTATS[demand_data_misses]} ($LOCAL_INTEGER_DEMANDDATAMISSESPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_misses]} - \u0394$LOCAL_INTEGER_DEMANDDATAMISSESDELTA (\u0394$LOCAL_INTEGER_DEMANDDATAMISSESDELTAPERCENTAGE%)"

 if ! ( [ "$LOCAL_INTEGER_DEMANDDATAHITSPERCENTAGE" = "0.00" ] && [ "$LOCAL_INTEGER_DEMANDDATAMISSESPERCENTAGE" = "0.00" ] )
 then
  echo "
   $(print_percentagebar20 $(( ${LOCAL_INTEGER_DEMANDDATAHITSPERCENTAGE:0:-3} / 5 )) "Hits ($LOCAL_INTEGER_DEMANDDATAHITSPERCENTAGE%)" "Misses ($LOCAL_INTEGER_DEMANDDATAMISSESPERCENTAGE%)")"
 fi

 echo -e "
 \u2022 Demand Metadata Hits (demand_metadata_hits):
      ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_hits]} ($LOCAL_INTEGER_DEMANDMETADATAHITSPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_hits]} - \u0394$LOCAL_INTEGER_DEMANDMETADATAHITSDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_DEMANDMETADATAHITSDELTA $LOCAL_INTEGER_DEMANDMETADATATOTALDELTA)%)
 \u2022 Demand Metadata Misses (demand_metadata_misses):
      ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_misses]} ($LOCAL_INTEGER_DEMANDMETADATAMISSESPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_misses]} - \u0394$LOCAL_INTEGER_DEMANDMETADATAMISSESDELTA (\u0394$LOCAL_INTEGER_DEMANDMETADATAMISSESDELTAPERCENTAGE%)"

 if ! ( [ "$LOCAL_INTEGER_DEMANDMETADATAHITSPERCENTAGE" = "0.00" ] && [ "$LOCAL_INTEGER_DEMANDMETADATAMISSESPERCENTAGE" = "0.00" ] )
 then
  echo "
   $(print_percentagebar20 $(( ${LOCAL_INTEGER_DEMANDMETADATAHITSPERCENTAGE:0:-3} / 5 )) "Hits ($LOCAL_INTEGER_DEMANDMETADATAHITSPERCENTAGE%)" "Misses ($LOCAL_INTEGER_DEMANDMETADATAMISSESPERCENTAGE%)")"
 fi

 echo -e "
 \u2022 Prefetch Data Hits (prefetch_data_hits):
      ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_hits]} ($LOCAL_INTEGER_PREFETCHDATAHITSPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_hits]} - \u0394$LOCAL_INTEGER_PREFETCHDATAHITSDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_PREFETCHDATAHITSDELTA $LOCAL_INTEGER_PREFETCHDATATOTALDELTA)%)
 \u2022 Prefetch Data Misses (prefetch_data_misses):
      ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_misses]} ($LOCAL_INTEGER_PREFETCHDATAMISSESPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_misses]} - \u0394$LOCAL_INTEGER_PREFETCHDATAMISSESDELTA (\u0394$LOCAL_INTEGER_PREFETCHDATAMISSESDELTAPERCENTAGE%)"

 if ! ( [ "$LOCAL_INTEGER_PREFETCHDATAHITSPERCENTAGE" = "0.00" ] && [ "$LOCAL_INTEGER_PREFETCHDATAMISSESPERCENTAGE" = "0.00" ] )
 then
  echo "
   $(print_percentagebar20 $(( ${LOCAL_INTEGER_PREFETCHDATAHITSPERCENTAGE:0:-3} / 5 )) "Hits ($LOCAL_INTEGER_PREFETCHDATAHITSPERCENTAGE%)" "Misses ($LOCAL_INTEGER_PREFETCHDATAMISSESPERCENTAGE%)")"
 fi

 echo -e "
 \u2022 Prefetch Metadata Hits (prefetch_metadata_hits):
      ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_hits]} ($LOCAL_INTEGER_PREFETCHMETADATAHITSPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_hits]} - \u0394$LOCAL_INTEGER_PREFETCHMETADATAHITSDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_PREFETCHMETADATAHITSDELTA $LOCAL_INTEGER_PREFETCHMETADATATOTALDELTA)%)
 \u2022 Prefetch Metadata Misses (prefetch_metadata_misses):
      ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_misses]} ($LOCAL_INTEGER_PREFETCHMETADATAMISSESPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_misses]} - \u0394$LOCAL_INTEGER_PREFETCHMETADATAMISSESDELTA (\u0394$LOCAL_INTEGER_PREFETCHMETADATAMISSESDELTAPERCENTAGE%)"

 if ! ( [ "$LOCAL_INTEGER_PREFETCHMETADATAHITSPERCENTAGE" = "0.00" ] && [ "$LOCAL_INTEGER_PREFETCHMETADATAMISSESPERCENTAGE" = "0.00" ] )
 then
  echo "
   $(print_percentagebar20 $(( ${LOCAL_INTEGER_PREFETCHMETADATAHITSPERCENTAGE:0:-3} / 5 )) "Hits ($LOCAL_INTEGER_PREFETCHMETADATAHITSPERCENTAGE%)" "Misses ($LOCAL_INTEGER_PREFETCHMETADATAMISSESPERCENTAGE%)")"
 fi
}

print_arcefficiency_realcachehitsbycachelist()
{
 local -n PARAMETER_ARRAY_ARCSTATS="$1"
 local -n PARAMETER_ARRAY_ARCSTATSLOG="$2"

 local LOCAL_INTEGER_HITS
 local LOCAL_INTEGER_HITSLOG
 local LOCAL_INTEGER_HITSDELTA
 local LOCAL_INTEGER_MRUPERCENTAGE
 local LOCAL_INTEGER_MFUPERCENTAGE
 local LOCAL_INTEGER_MRUGHOSTPERCENTAGE
 local LOCAL_INTEGER_MFUGHOSTPERCENTAGE
 local LOCAL_INTEGER_MRUDELTA
 local LOCAL_INTEGER_MFUDELTA
 local LOCAL_INTEGER_MRUGHOSTDELTA
 local LOCAL_INTEGER_MFUGHOSTDELTA

 LOCAL_INTEGER_HITS=$(( ${PARAMETER_ARRAY_ARCSTATS[mru_hits]} + ${PARAMETER_ARRAY_ARCSTATS[mfu_hits]} + ${PARAMETER_ARRAY_ARCSTATS[mru_ghost_hits]} + ${PARAMETER_ARRAY_ARCSTATS[mfu_ghost_hits]} ))
 LOCAL_INTEGER_HITSLOG=$(( ${PARAMETER_ARRAY_ARCSTATSLOG[mru_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[mfu_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[mru_ghost_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[mfu_ghost_hits]} ))
 LOCAL_INTEGER_HITSDELTA=$(( LOCAL_INTEGER_HITS - LOCAL_INTEGER_HITSLOG ))

 LOCAL_INTEGER_MRUPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[mru_hits]} $LOCAL_INTEGER_HITS)
 LOCAL_INTEGER_MFUPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[mfu_hits]} $LOCAL_INTEGER_HITS)
 LOCAL_INTEGER_MRUGHOSTPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[mru_ghost_hits]} $LOCAL_INTEGER_HITS)
 LOCAL_INTEGER_MFUGHOSTPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[mfu_ghost_hits]} $LOCAL_INTEGER_HITS)

 LOCAL_INTEGER_MRUDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[mru_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[mru_hits]} ))
 LOCAL_INTEGER_MFUDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[mfu_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[mfu_hits]} ))
 LOCAL_INTEGER_MRUGHOSTDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[mru_ghost_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[mru_ghost_hits]} ))
 LOCAL_INTEGER_MFUGHOSTDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[mfu_ghost_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[mfu_ghost_hits]} ))

 echo -e "
ARC Efficiency - Cache Hits by Cache List:
 \u2022 Cache Hits (mru_hits + mfu_hits + mru_ghost_hits + mfu_ghost_hits):
      $LOCAL_INTEGER_HITS \u279f $LOCAL_INTEGER_HITSLOG - \u0394$LOCAL_INTEGER_HITSDELTA
 \u2022 Most Recently Used (mru_hits):
    [ Return Customer ]
      ${PARAMETER_ARRAY_ARCSTATS[mru_hits]} ($LOCAL_INTEGER_MRUPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[mru_hits]} - \u0394$LOCAL_INTEGER_MRUDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_MRUDELTA $LOCAL_INTEGER_HITSDELTA)%)
 \u2022 Most Frequently Used (mfu_hits):
    [ Frequent Customer ]
      ${PARAMETER_ARRAY_ARCSTATS[mfu_hits]} ($LOCAL_INTEGER_MFUPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[mfu_hits]} - \u0394$LOCAL_INTEGER_MFUDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_MFUDELTA $LOCAL_INTEGER_HITSDELTA)%)
 \u2022 Most Recently Used Ghost (mru_ghost_hits):
    [ Return Customer Evicted, Now Back ]
      ${PARAMETER_ARRAY_ARCSTATS[mru_ghost_hits]} ($LOCAL_INTEGER_MRUGHOSTPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[mru_ghost_hits]} - \u0394$LOCAL_INTEGER_MRUGHOSTDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_MRUGHOSTDELTA $LOCAL_INTEGER_HITSDELTA)%)
 \u2022 Most Frequently Used Ghost (mfu_ghost_hits):
    [ Frequent Customer Evicted, Now Back ]
      ${PARAMETER_ARRAY_ARCSTATS[mfu_ghost_hits]} ($LOCAL_INTEGER_MFUGHOSTPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[mfu_ghost_hits]} - \u0394$LOCAL_INTEGER_MFUGHOSTDELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_MFUGHOSTDELTA $LOCAL_INTEGER_HITSDELTA)%)"

 if [ "$LOCAL_INTEGER_HITS" -gt 0 ]
 then
  echo "
   $(print_4percentagebarmaximum20 $(( ${LOCAL_INTEGER_MRUPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_MFUPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_MRUGHOSTPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_MFUGHOSTPERCENTAGE:0:-3} / 5 )) "MRU ($LOCAL_INTEGER_MRUPERCENTAGE%), MFU ($LOCAL_INTEGER_MFUPERCENTAGE%)" "MRU Ghost ($LOCAL_INTEGER_MRUGHOSTPERCENTAGE%), MFU Ghost ($LOCAL_INTEGER_MFUGHOSTPERCENTAGE%)")"
 fi
}


print_arcefficiency_cachehitsbydatatype()
{
 local -n PARAMETER_ARRAY_ARCSTATS="$1"
 local -n PARAMETER_ARRAY_ARCSTATSLOG="$2"

 local LOCAL_INTEGER_HITSDELTA
 local LOCAL_INTEGER_HITSDEMANDDATAPERCENTAGE
 local LOCAL_INTEGER_HITSDEMANDMETADATAPERCENTAGE
 local LOCAL_INTEGER_HITSPREFETCHDATAPERCENTAGE
 local LOCAL_INTEGER_HITSPREFETCHMETADATAPERCENTAGE
 local LOCAL_INTEGER_DEMANDDATADELTA
 local LOCAL_INTEGER_DEMANDMETADATADELTA
 local LOCAL_INTEGER_PREFETCHDATADELTA
 local LOCAL_INTEGER_PREFETCHMETADATADELTA

 LOCAL_INTEGER_HITSDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[hits]} ))

 LOCAL_INTEGER_HITSDEMANDDATAPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[demand_data_hits]} ${PARAMETER_ARRAY_ARCSTATS[hits]})
 LOCAL_INTEGER_HITSDEMANDMETADATAPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_hits]} ${PARAMETER_ARRAY_ARCSTATS[hits]})
 LOCAL_INTEGER_HITSPREFETCHDATAPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_hits]} ${PARAMETER_ARRAY_ARCSTATS[hits]})
 LOCAL_INTEGER_HITSPREFETCHMETADATAPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_hits]} ${PARAMETER_ARRAY_ARCSTATS[hits]})

 LOCAL_INTEGER_HITSDEMANDDATADELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_data_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_hits]} ))
 LOCAL_INTEGER_HITSDEMANDMETADATADELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_hits]} ))
 LOCAL_INTEGER_HITSPREFETCHDATADELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_hits]} ))
 LOCAL_INTEGER_HITSPREFETCHMETADATADELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_hits]} ))

 echo -e "
ARC Efficiency - Cache Hits by Data Type:
 \u2022 Cache Hits (hits):
      ${PARAMETER_ARRAY_ARCSTATS[hits]} \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[hits]} - \u0394$LOCAL_INTEGER_HITSDELTA
 \u2022 Demand Data Hits (demand_data_hits):
      ${PARAMETER_ARRAY_ARCSTATS[demand_data_hits]} ($LOCAL_INTEGER_HITSDEMANDDATAPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_hits]} - \u0394$LOCAL_INTEGER_HITSDEMANDDATADELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_HITSDEMANDDATADELTA $LOCAL_INTEGER_HITSDELTA)%)
 \u2022 Demand Metadata Hits (demand_metadata_hits):
      ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_hits]} ($LOCAL_INTEGER_HITSDEMANDMETADATAPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_hits]} - \u0394$LOCAL_INTEGER_HITSDEMANDMETADATADELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_HITSDEMANDMETADATADELTA $LOCAL_INTEGER_HITSDELTA)%)
 \u2022 Prefetch Data Hits (prefetch_data_hits):
      ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_hits]} ($LOCAL_INTEGER_HITSPREFETCHDATAPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_hits]} - \u0394$LOCAL_INTEGER_HITSPREFETCHDATADELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_HITSPREFETCHDATADELTA $LOCAL_INTEGER_HITSDELTA)%)
 \u2022 Prefetch Metadata Hits (prefetch_metadata_hits):
      ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_hits]} ($LOCAL_INTEGER_HITSPREFETCHMETADATAPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_hits]} - \u0394$LOCAL_INTEGER_HITSPREFETCHMETADATADELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_HITSPREFETCHMETADATADELTA $LOCAL_INTEGER_HITSDELTA)%)"

 if [ "${PARAMETER_ARRAY_ARCSTATS[hits]}" -gt 0 ]
 then
  echo "
   $(print_4percentagebarmaximum20 $(( ${LOCAL_INTEGER_HITSDEMANDDATAPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_HITSDEMANDMETADATAPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_HITSPREFETCHDATAPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_HITSPREFETCHMETADATAPERCENTAGE:0:-3} / 5 )) "DDH ($LOCAL_INTEGER_HITSDEMANDDATAPERCENTAGE%), DMH ($LOCAL_INTEGER_HITSDEMANDMETADATAPERCENTAGE%)" "PDH ($LOCAL_INTEGER_HITSPREFETCHDATAPERCENTAGE%), PMH ($LOCAL_INTEGER_HITSPREFETCHMETADATAPERCENTAGE%)")"
 fi
}

print_arcefficiency_cachemissesbydatatype()
{
 local -n PARAMETER_ARRAY_ARCSTATS="$1"
 local -n PARAMETER_ARRAY_ARCSTATSLOG="$2"

 local LOCAL_INTEGER_MISSESDELTA
 local LOCAL_INTEGER_MISSESDEMANDDATAPERCENTAGE
 local LOCAL_INTEGER_MISSESDEMANDMETADATAPERCENTAGE
 local LOCAL_INTEGER_MISSESPREFETCHDATAPERCENTAGE
 local LOCAL_INTEGER_MISSESPREFETCHMETADATAPERCENTAGE
 local LOCAL_INTEGER_DEMANDDATADELTA
 local LOCAL_INTEGER_DEMANDMETADATADELTA
 local LOCAL_INTEGER_PREFETCHDATADELTA
 local LOCAL_INTEGER_PREFETCHMETADATADELTA

 LOCAL_INTEGER_MISSESDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[misses]} ))

 LOCAL_INTEGER_MISSESDEMANDDATAPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[demand_data_misses]} ${PARAMETER_ARRAY_ARCSTATS[misses]})
 LOCAL_INTEGER_MISSESDEMANDMETADATAPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_misses]} ${PARAMETER_ARRAY_ARCSTATS[misses]})
 LOCAL_INTEGER_MISSESPREFETCHDATAPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_misses]} ${PARAMETER_ARRAY_ARCSTATS[misses]})
 LOCAL_INTEGER_MISSESPREFETCHMETADATAPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_misses]} ${PARAMETER_ARRAY_ARCSTATS[misses]})

 LOCAL_INTEGER_MISSESDEMANDDATADELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_data_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_misses]} ))
 LOCAL_INTEGER_MISSESDEMANDMETADATADELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_misses]} ))
 LOCAL_INTEGER_MISSESPREFETCHDATADELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_misses]} ))
 LOCAL_INTEGER_MISSESPREFETCHMETADATADELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_misses]} ))

 echo -e "
ARC Efficiency - Cache Misses by Data Type:
 \u2022 Cache Misses (misses):
      ${PARAMETER_ARRAY_ARCSTATS[misses]} \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[misses]} - \u0394$LOCAL_INTEGER_MISSESDELTA
 \u2022 Demand Data Misses (demand_data_misses):
      ${PARAMETER_ARRAY_ARCSTATS[demand_data_misses]} ($LOCAL_INTEGER_MISSESDEMANDDATAPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[demand_data_misses]} - \u0394$LOCAL_INTEGER_MISSESDEMANDDATADELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_MISSESDEMANDDATADELTA $LOCAL_INTEGER_MISSESDELTA)%)
 \u2022 Demand Metadata Misses (demand_metadata_misses):
      ${PARAMETER_ARRAY_ARCSTATS[demand_metadata_misses]} ($LOCAL_INTEGER_MISSESDEMANDMETADATAPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[demand_metadata_misses]} - \u0394$LOCAL_INTEGER_MISSESDEMANDMETADATADELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_MISSESDEMANDMETADATADELTA $LOCAL_INTEGER_MISSESDELTA)%)
 \u2022 Prefetch Data Misses (prefetch_data_misses):
      ${PARAMETER_ARRAY_ARCSTATS[prefetch_data_misses]} ($LOCAL_INTEGER_MISSESPREFETCHDATAPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_data_misses]} - \u0394$LOCAL_INTEGER_MISSESPREFETCHDATADELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_MISSESPREFETCHDATADELTA $LOCAL_INTEGER_MISSESDELTA)%)
 \u2022 Prefetch Metadata Misses (prefetch_metadata_misses):
      ${PARAMETER_ARRAY_ARCSTATS[prefetch_metadata_misses]} ($LOCAL_INTEGER_MISSESPREFETCHMETADATAPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[prefetch_metadata_misses]} - \u0394$LOCAL_INTEGER_MISSESPREFETCHMETADATADELTA (\u0394$(calculate_percentage $LOCAL_INTEGER_MISSESPREFETCHMETADATADELTA $LOCAL_INTEGER_MISSESDELTA)%)"

 if [ "${PARAMETER_ARRAY_ARCSTATS[misses]}" -gt 0 ]
 then
  echo "
   $(print_4percentagebarmaximum20 $(( ${LOCAL_INTEGER_MISSESDEMANDDATAPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_MISSESDEMANDMETADATAPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_MISSESPREFETCHDATAPERCENTAGE:0:-3} / 5 )) $(( ${LOCAL_INTEGER_MISSESPREFETCHMETADATAPERCENTAGE:0:-3} / 5 )) "DDM ($LOCAL_INTEGER_MISSESDEMANDDATAPERCENTAGE%), DMM ($LOCAL_INTEGER_MISSESDEMANDMETADATAPERCENTAGE%)" "PDM ($LOCAL_INTEGER_MISSESPREFETCHDATAPERCENTAGE%), PMM ($LOCAL_INTEGER_MISSESPREFETCHMETADATAPERCENTAGE%)")"
 fi
}

print_arc_efficiencyl2()
{
 local -n PARAMETER_ARRAY_ARCSTATS="$1"
 local -n PARAMETER_ARRAY_ARCSTATSLOG="$2"

 local LOCAL_INTEGER_L2TOTAL
 local LOCAL_INTEGER_L2TOTALLOG
 local LOCAL_INTEGER_L2TOTALDELTA
 local LOCAL_INTEGER_L2HITSDELTA
 local LOCAL_INTEGER_L2MISSESDELTA

 LOCAL_INTEGER_L2TOTAL=$(( ${PARAMETER_ARRAY_ARCSTATS[l2_hits]} + ${PARAMETER_ARRAY_ARCSTATS[l2_misses]} ))
 LOCAL_INTEGER_L2TOTALLOG=$(( ${PARAMETER_ARRAY_ARCSTATSLOG[l2_hits]} + ${PARAMETER_ARRAY_ARCSTATSLOG[l2_misses]} ))
 LOCAL_INTEGER_L2TOTALDELTA=$(( $LOCAL_INTEGER_L2TOTAL - $LOCAL_INTEGER_L2TOTALLOG))

 LOCAL_INTEGER_L2HITSPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[l2_hits]} $LOCAL_INTEGER_TOTAL)
 LOCAL_INTEGER_L2HITSDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[l2_hits]} - ${PARAMETER_ARRAY_ARCSTATSLOG[l2_hits]} ))
 LOCAL_INTEGER_L2HITSDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_L2HITSDELTA $LOCAL_INTEGER_TOTALDELTA)

 LOCAL_INTEGER_L2MISSESPERCENTAGE=$(calculate_percentage ${PARAMETER_ARRAY_ARCSTATS[l2_misses]} $LOCAL_INTEGER_TOTAL)
 LOCAL_INTEGER_L2MISSESDELTA=$(( ${PARAMETER_ARRAY_ARCSTATS[l2_misses]} - ${PARAMETER_ARRAY_ARCSTATSLOG[l2_misses]} ))
 LOCAL_INTEGER_L2MISSESDELTAPERCENTAGE=$(calculate_percentage $LOCAL_INTEGER_L2MISSESDELTA $LOCAL_INTEGER_TOTALDELTA)


 echo -e "
L2ARC Efficiency:
 \u2022 L2 Cache Access Total:
      $LOCAL_INTEGER_L2TOTAL \u279f $LOCAL_INTEGER_L2TOTALLOG - \u0394$LOCAL_INTEGER_L2TOTALDELTA
 \u2022 L2 Cache Hits (l2_hits):
      ${PARAMETER_ARRAY_ARCSTATS[l2_hits]} ($LOCAL_INTEGER_L2HITSPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[l2_hits]} - \u0394$LOCAL_INTEGER_L2HITSDELTA (\u0394$LOCAL_INTEGER_L2HITSDELTAPERCENTAGE%)
 \u2022 L2 Cache Misses (misses):
      ${PARAMETER_ARRAY_ARCSTATS[l2_misses]} ($LOCAL_INTEGER_L2MISSESPERCENTAGE%) \u279f ${PARAMETER_ARRAY_ARCSTATSLOG[l2_misses]} - \u0394$LOCAL_INTEGER_L2MISSESDELTA (\u0394$LOCAL_INTEGER_L2MISSESDELTAPERCENTAGE%)"

 if ! ( [ "$LOCAL_INTEGER_L2HITSPERCENTAGE" = "0.00" ] && [ "$LOCAL_INTEGER_L2MISSESPERCENTAGE" = "0.00" ] )
 then
  echo "
   $(print_percentagebar20 $(( ${LOCAL_INTEGER_L2HITSPERCENTAGE:0:-3} / 5 )) "Hits ($LOCAL_INTEGER_L2HITSPERCENTAGE%)" "Misses ($LOCAL_INTEGER_L2MISSESPERCENTAGE%)")"
 fi
}
