#!/bin/bash

declare -A GLOBAL_ARRAY_ARCSTATS
declare -a GLOBAL_ARRAY_ARCSTATSINDEX
declare -A GLOBAL_ARRAY_ARCSTATSLOG


zpool_print_status()
{
 /sbin/zpool status
}

zpool_print_verbosediostat()
{
 /sbin/zpool iostat -v
}

zfs_getarray_arcstats()
{
 local LOCAL_ARRAY_ARCSTATS
 local LOCAL_ITEMSTRING_ARCSTATS
 local LOCAL_STRING_ARCSTATSVARIABLENAME

 LOCAL_ARRAY_ARCSTATS=( $(/bin/grep -e 'hits ' -e 'misses ' --no-group-separator /proc/spl/kstat/zfs/arcstats) )

 for LOCAL_ITEMSTRING_ARCSTATS in "${LOCAL_ARRAY_ARCSTATS[@]}"
 do
  LOCAL_STRING_ARCSTATSVARIABLENAME="${LOCAL_ITEMSTRING_ARCSTATS%% *}"

  if [ ${LOCAL_STRING_ARCSTATSVARIABLENAME: -4} == "hits" ]
  then
   GLOBAL_ARRAY_ARCSTATSINDEX=("${GLOBAL_ARRAY_ARCSTATSINDEX[@]}" "$LOCAL_STRING_ARCSTATSVARIABLENAME")
  fi

  GLOBAL_ARRAY_ARCSTATS["$LOCAL_STRING_ARCSTATSVARIABLENAME"]="${LOCAL_ITEMSTRING_ARCSTATS##* }"
 done
}

zfs_getdate_arcstatslog()
{
 local LOCAL_FILE_ARCSTATSLOG="$1"

 /usr/bin/head -n 1 "$LOCAL_FILE_ARCSTATSLOG"
}

zfs_getarray_arcstatslog()
{
 local LOCAL_FILE_ARCSTATSLOG="$1"

 local LOCAL_ARRAY_ARCSTATSLOG
 local LOCAL_ITEMSTRING_ARCSTATSLOG

 LOCAL_ARRAY_ARCSTATSLOG=( $(/bin/cat "$LOCAL_FILE_ARCSTATSLOG") )

 for LOCAL_ITEMSTRING_ARCSTATSLOG in "${LOCAL_ARRAY_ARCSTATSLOG[@]}"
 do
  GLOBAL_ARRAY_ARCSTATSLOG["${LOCAL_ITEMSTRING_ARCSTATSLOG%% *}"]="${LOCAL_ITEMSTRING_ARCSTATSLOG##* }"
 done
}

zfs_write_arcstatslog()
{
 local LOCAL_STRING_DATETIME="$1"
 local LOCAL_FILE_ARCSTATSLOG="$2"

 local LOCAL_ITEMSTRING_ARCSTATSLOG

 echo "$LOCAL_STRING_DATETIME" 1>"$LOCAL_FILE_ARCSTATSLOG"

 for LOCAL_ITEMKEYSTRING_ARCSTATS in "${!GLOBAL_ARRAY_ARCSTATS[@]}"
 do
  echo "$LOCAL_ITEMKEYSTRING_ARCSTATS ${GLOBAL_ARRAY_ARCSTATS[$LOCAL_ITEMKEYSTRING_ARCSTATS]}" 1>>"$LOCAL_FILE_ARCSTATSLOG"
 done
}

zfs_print_arcstats()
{
 local LOCAL_ITEM_ARCSTATINDEX
 local LOCAL_NUMBER_HITSVALUE
 local LOCAL_NUMBER_MISSESVALUE
 local LOCAL_RATIO_HITS
 local LOCAL_RATIO_MISSES

 for LOCAL_ITEM_ARCSTATINDEX in "${GLOBAL_ARRAY_ARCSTATSINDEX[@]}"
 do
  echo

  if [ -z "${GLOBAL_ARRAY_ARCSTATS[${LOCAL_ITEM_ARCSTATINDEX:0:-4}misses]}" ]
  then
   echo "$LOCAL_ITEM_ARCSTATINDEX: ${GLOBAL_ARRAY_ARCSTATS[$LOCAL_ITEM_ARCSTATINDEX]}"
  else
   LOCAL_NUMBER_HITSVALUE="${GLOBAL_ARRAY_ARCSTATS[$LOCAL_ITEM_ARCSTATINDEX]}"
   LOCAL_NUMBER_MISSESVALUE="${GLOBAL_ARRAY_ARCSTATS[${LOCAL_ITEM_ARCSTATINDEX:0:-4}misses]}"

   echo "$LOCAL_ITEM_ARCSTATINDEX: $LOCAL_NUMBER_HITSVALUE"
   echo "${LOCAL_ITEM_ARCSTATINDEX:0:-4}misses: $LOCAL_NUMBER_MISSESVALUE"

   if [ "$LOCAL_NUMBER_HITSVALUE" -ne 0 ] 2>/dev/null && [ "$LOCAL_NUMBER_MISSESVALUE" -ne 0 ] 2>/dev/null
   then
    let "LOCAL_RATIO_HITS=($LOCAL_NUMBER_HITSVALUE*10000)/($LOCAL_NUMBER_HITSVALUE+$LOCAL_NUMBER_MISSESVALUE)"
    let "LOCAL_RATIO_MISSES=($LOCAL_NUMBER_MISSESVALUE*10000)/($LOCAL_NUMBER_HITSVALUE+$LOCAL_NUMBER_MISSESVALUE)"

    echo "hit ration: ${LOCAL_RATIO_HITS:0:-2}.${LOCAL_RATIO_HITS: -2}%"
    echo "miss ration: ${LOCAL_RATIO_MISSES:0:-2}.${LOCAL_RATIO_MISSES: -2}%"
   fi
  fi
 done
}

zfs_print_arcstatslog()
{
 local LOCAL_ITEM_ARCSTATINDEX
 local LOCAL_NUMBER_HITSVALUE
 local LOCAL_NUMBER_MISSESVALUE
 local LOCAL_RATIO_HITS
 local LOCAL_RATIO_MISSES
 local LOCAL_NUMBER_HITSLOGVALUE
 local LOCAL_NUMBER_MISSESLOGVALUE
 local LOCAL_NUMBER_HITSDELTA
 local LOCAL_NUMBER_MISSESDELTA
 local LOCAL_RATIO_HITSDELTA
 local LOCAL_RATIO_MISSESDELTA

 for LOCAL_ITEM_ARCSTATINDEX in "${GLOBAL_ARRAY_ARCSTATSINDEX[@]}"
 do
  echo

  if [ -z "${GLOBAL_ARRAY_ARCSTATS[${LOCAL_ITEM_ARCSTATINDEX:0:-4}misses]}" ]
  then
   echo -n "$LOCAL_ITEM_ARCSTATINDEX: ${GLOBAL_ARRAY_ARCSTATS[$LOCAL_ITEM_ARCSTATINDEX]}"

   if [ ! -z "${GLOBAL_ARRAY_ARCSTATSLOG[$LOCAL_ITEM_ARCSTATINDEX]}" ]
   then
    echo " (${GLOBAL_ARRAY_ARCSTATSLOG[$LOCAL_ITEM_ARCSTATINDEX]})"
   else
    echo
   fi
  else
   LOCAL_NUMBER_HITSVALUE="${GLOBAL_ARRAY_ARCSTATS[$LOCAL_ITEM_ARCSTATINDEX]}"
   LOCAL_NUMBER_HITSLOGVALUE="${GLOBAL_ARRAY_ARCSTATSLOG[$LOCAL_ITEM_ARCSTATINDEX]}"
   LOCAL_NUMBER_MISSESVALUE="${GLOBAL_ARRAY_ARCSTATS[${LOCAL_ITEM_ARCSTATINDEX:0:-4}misses]}"
   LOCAL_NUMBER_MISSESLOGVALUE="${GLOBAL_ARRAY_ARCSTATSLOG[${LOCAL_ITEM_ARCSTATINDEX:0:-4}misses]}"

   echo -n "$LOCAL_ITEM_ARCSTATINDEX: $LOCAL_NUMBER_HITSVALUE"

   if [ ! -z "$LOCAL_NUMBER_HITSLOGVALUE" ]
   then
    echo " ($LOCAL_NUMBER_HITSLOGVALUE)"
   else
    echo
   fi

   echo -n "${LOCAL_ITEM_ARCSTATINDEX:0:-4}misses: $LOCAL_NUMBER_MISSESVALUE"

   if [ ! -z "$LOCAL_NUMBER_MISSESLOGVALUE" ]
   then
    echo " ($LOCAL_NUMBER_MISSESLOGVALUE)"
   else
    echo
   fi

   if [ "$LOCAL_NUMBER_HITSVALUE" -ne 0 ] 2>/dev/null && [ "$LOCAL_NUMBER_MISSESVALUE" -ne 0 ] 2>/dev/null
   then
    let "LOCAL_RATIO_HITS=($LOCAL_NUMBER_HITSVALUE*10000)/($LOCAL_NUMBER_HITSVALUE+$LOCAL_NUMBER_MISSESVALUE)"
    let "LOCAL_RATIO_MISSES=($LOCAL_NUMBER_MISSESVALUE*10000)/($LOCAL_NUMBER_HITSVALUE+$LOCAL_NUMBER_MISSESVALUE)"
   else
    LOCAL_RATIO_HITS=""
    LOCAL_RATIO_MISSES=""
   fi

   if [ "$LOCAL_NUMBER_HITSLOGVALUE" -ne 0 ] 2>/dev/null && [ "$LOCAL_NUMBER_MISSESLOGVALUE" -ne 0 ] 2>/dev/null
   then
    let "LOCAL_NUMBER_HITSDELTA=$LOCAL_NUMBER_HITSVALUE-$LOCAL_NUMBER_HITSLOGVALUE"
    let "LOCAL_NUMBER_MISSESDELTA=$LOCAL_NUMBER_MISSESVALUE-$LOCAL_NUMBER_MISSESLOGVALUE"

    if [ "$LOCAL_NUMBER_HITSDELTA" -ne 0 ] 2>/dev/null && [ "$LOCAL_NUMBER_MISSESDELTA" -ne 0 ] 2>/dev/null
    then
     let "LOCAL_RATIO_HITSDELTA=($LOCAL_NUMBER_HITSDELTA*10000)/($LOCAL_NUMBER_HITSDELTA+$LOCAL_NUMBER_MISSESDELTA)"
     let "LOCAL_RATIO_MISSESDELTA=($LOCAL_NUMBER_MISSESDELTA*10000)/($LOCAL_NUMBER_HITSDELTA+$LOCAL_NUMBER_MISSESDELTA)"
    else
     LOCAL_RATIO_HITSDELTA=""
     LOCAL_RATIO_MISSESDELTA=""
    fi
   else
    LOCAL_RATIO_HITSLOG=""
    LOCAL_RATIO_MISSESLOG=""
   fi

   if [ ! -z "$LOCAL_RATIO_HITS" ] || [ ! -z "$LOCAL_RATIO_HITSLOG" ]
   then
    echo -n "hit ration:"

    if [ ! -z "$LOCAL_RATIO_HITS" ]
    then
     echo -n " ${LOCAL_RATIO_HITS:0:-2}.${LOCAL_RATIO_HITS: -2}%"
    else
     echo -n " -"
    fi

    if [ ! -z "$LOCAL_RATIO_HITSDELTA" ]
    then
     echo -e " (\u0394${LOCAL_RATIO_HITSDELTA:0:-2}.${LOCAL_RATIO_HITSDELTA: -2}%)"
    else
     echo
    fi

    echo -n "miss ration:"

    if [ ! -z "$LOCAL_RATIO_MISSES" ]
    then
     echo -n " ${LOCAL_RATIO_MISSES:0:-2}.${LOCAL_RATIO_MISSES: -2}%"
    else
     echo -n " -"
    fi

    if [ ! -z "$LOCAL_RATIO_MISSESDELTA" ]
    then
     echo -e " (\u0394${LOCAL_RATIO_MISSESDELTA:0:-2}.${LOCAL_RATIO_MISSESDELTA: -2}%)"
    else
     echo
    fi
   fi
  fi
 done
}
