#!/bin/bash

convert_byte_megabyte()
{
 local PARAMETER_INTEGER_BYTE="$1"

 local LOCAL_INTEGER_HUNDREDMEGABYTE

 LOCAL_INTEGER_HUNDREDMEGABYTE="$(( PARAMETER_INTEGER_BYTE * 100 / 1048576 ))"

 echo "${LOCAL_INTEGER_HUNDREDMEGABYTE:0:-2}.${LOCAL_INTEGER_HUNDREDMEGABYTE: -2}"
}

convert_file_namevalue()
{
 local PARAMETER_FILE_SOURCE="$1"
 local -n PARAMETER_STRING_FIRSTLINE="$2"
 local -n PARAMETER_ARRAY_RESULT="$3"

 local LOCAL_BOOLEAN_FIRSTLINE
 local LOCAL_STRING_SOURCE
 local LOCAL_LINESTRING_SOURCE
 local LOCAL_STRING_NAME
 local LOCAL_STRING_VALUE

 PARAMETER_ARRAY_RESULT=()
 LOCAL_BOOLEAN_FIRSTLINE=true

 LOCAL_STRING_SOURCE=$(<"$PARAMETER_FILE_SOURCE")

 IFS=$'\n'
 for LOCAL_LINESTRING_SOURCE in $LOCAL_STRING_SOURCE
 do
  if $LOCAL_BOOLEAN_FIRSTLINE
  then
   PARAMETER_STRING_FIRSTLINE="$LOCAL_LINESTRING_SOURCE"
   LOCAL_BOOLEAN_FIRSTLINE=false
   continue
  fi

  LOCAL_STRING_NAME="${LOCAL_LINESTRING_SOURCE%% *}"
  LOCAL_STRING_VARIABLE="${LOCAL_LINESTRING_SOURCE##* }"

  PARAMETER_ARRAY_RESULT["$LOCAL_STRING_NAME"]="$LOCAL_STRING_VARIABLE"
 done
}
