#!/bin/bash

/sbin/zpool status
echo
/sbin/zpool iostat -v

IFS=$'\n'
GLOBAL_ARRAY_ARCSTAT=( $(/bin/grep -B1 'misses' --no-group-separator /proc/spl/kstat/zfs/arcstats ) )

for (( GLOBAL_INDEX_ARRAYPAIRS=0; GLOBAL_INDEX_ARRAYPAIRS<${#GLOBAL_ARRAY_ARCSTAT[@]}; GLOBAL_INDEX_ARRAYPAIRS=GLOBAL_INDEX_ARRAYPAIRS+2 ))
do
 echo

 GLOBAL_STRING_HITSNAME="${GLOBAL_ARRAY_ARCSTAT[$GLOBAL_INDEX_ARRAYPAIRS]%% *}"
 GLOBAL_STRING_MISSESNAME="${GLOBAL_ARRAY_ARCSTAT[$GLOBAL_INDEX_ARRAYPAIRS+1]%% *}"
 GLOBAL_NUMBER_HITSVALUE="${GLOBAL_ARRAY_ARCSTAT[$GLOBAL_INDEX_ARRAYPAIRS]##* }"
 GLOBAL_NUMBER_MISSESVALUE="${GLOBAL_ARRAY_ARCSTAT[$GLOBAL_INDEX_ARRAYPAIRS+1]##* }"

 echo "$GLOBAL_STRING_HITSNAME: $GLOBAL_NUMBER_HITSVALUE"
 echo "$GLOBAL_STRING_MISSESNAME: $GLOBAL_NUMBER_MISSESVALUE"

 if [ "$GLOBAL_NUMBER_HITVALUE" != "0" ] && [ "$GLOBAL_NUMBER_MISSESVALUE" != "0" ]
 then
  let "GLOBAL_RATIO_ARCHITS=($GLOBAL_NUMBER_HITSVALUE*10000)/($GLOBAL_NUMBER_HITSVALUE+$GLOBAL_NUMBER_MISSESVALUE)"
  let "GLOBAL_RATIO_ARCMISSES=($GLOBAL_NUMBER_MISSESVALUE*10000)/($GLOBAL_NUMBER_HITSVALUE+$GLOBAL_NUMBER_MISSESVALUE)"

  echo "hit ration: ${GLOBAL_RATIO_ARCHITS:0:-2}.${GLOBAL_RATIO_ARCHITS: -2} %"
  echo "miss ration: ${GLOBAL_RATIO_ARCMISSES:0:-2}.${GLOBAL_RATIO_ARCMISSES: -2} %"
 fi
done
